version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn --version

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install --frozen-lockfile
      - run: yarn run lerna bootstrap

      - run: cd packages/abortable && yarn build
      - run: cd packages/abortable-networking && yarn build
      - run: cd packages/with-async && yarn build
      - run: yarn lint
      - run: yarn prettier --list-different
      - run: yarn test --coverage

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
